version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - open-dynaMIX
  ignore:
  - dependency-name: django
    versions:
    - ">=3"
  - dependency-name: black
    versions:
    - 20.8b1
    - 21.4b0
    - 21.4b1
  - dependency-name: gitlint
    versions:
    - 0.15.0
  - dependency-name: preview-generator
    versions:
    - 0.15.4
  - dependency-name: django-extensions
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.1.post1
  - dependency-name: minio
    versions:
    - 7.0.1
    - 7.0.2
  - dependency-name: pre-commit
    versions:
    - 2.10.0
    - 2.10.1
    - 2.11.0
    - 2.11.1
  - dependency-name: isort
    versions:
    - 5.7.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - open-dynaMIX
  ignore:
  - dependency-name: python
    versions:
    - ">=3.7"
  - dependency-name: python
    versions:
    - 3.6.12.pre.slim.pre.buster
  commit-message:
    prefix: chore
    include: scope
