repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: gitlint
        stages: [commit-msg]
        name: gitlint
        description: Validate commit lint
        entry: gitlint --msg-filename
        language: system
