---
services:
  db:
    environment:
      - POSTGRES_PASSWORD=alexandria
    ports:
      - "5432:5432"

  media-files:
    image: alpine:3.24.2@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
    restart: "no"
    volumes:
      - uploads:/media/uploads
    entrypoint: |
      /bin/sh -c "chown -R ${UID}:${UID} /media"

  alexandria: &alexandria
    build:
      context: .
      target: dev
    user: "${UID:?Set UID env variable to your user id}"
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
      - uploads:/media/uploads
    depends_on:
      - media-files
    environment:
      - ENV=dev
      - DEBUG=true
      - ALEXANDRIA_DEV_AUTH_BACKEND=true
      - ALEXANDRIA_ALLOW_ANONYMOUS_WRITE=true
      - ALEXANDRIA_ENABLE_CONTENT_SEARCH=true
      - PYTHONUNBUFFERED=1
      - CELERY_RDB_HOST=0.0.0.0. # to be able to telnet from outside the container
      - ALEXANDRIA_USE_MANABI=true
      - ALEXANDRIA_S3_ENDPOINT_URL=http://garage:3900
      - ALEXANDRIA_S3_ACCESS_KEY=s3storageadmin
      - ALEXANDRIA_S3_SECRET_KEY=s3storageSecretKey
      - ALEXANDRIA_S3_REGION_NAME=garage

  garage:
    environment:
      - GARAGE_DEFAULT_ACCESS_KEY=s3storageadmin
      - GARAGE_DEFAULT_SECRET_KEY=s3storageSecretKey
      - GARAGE_DEFAULT_BUCKET=alexandria-media

  clamav:
    environment:
      - CONCURRENT_DATABASE_RELOAD=false
      - ENABLE_DEFINITIONS_UPDATE=false

  celery:
    <<: *alexandria
    ports:
      - "6900-7000:6900-7000"

volumes:
  uploads:
