---
x-alexandria-common: &alexandria-common
  depends_on:
    - db
    - garage
    - tika
    - clamav
    - dms
  environment:
    - DATABASE_HOST=db
    - DATABASE_PORT=5432
    - TIKA_CLIENT_ONLY=true
    - TIKA_SERVER_ENDPOINT=http://tika:9998
    - ALEXANDRIA_CLAMD_TCP_ADDR=clamav

services:
  db:
    image: postgres:18.6-alpine3.23@sha256:885cf05d376c7cf27afef02073e6bdac3841252537f16e244fd1c1e6a7c99fb1
    environment:
      - POSTGRES_USER=alexandria
      # following option is a must to configure on production system:
      # https://hub.docker.com/_/postgres
      # - POSTGRES_PASSWORD=
    volumes:
      - dbdata18:/var/lib/postgresql

  alexandria:
    <<: *alexandria-common
    image: ghcr.io/projectcaluma/alexandria:dev
    ports:
      - "8000:8000"

  dms:
    image: ghcr.io/adfinis/document-merge-service:10.0.1@sha256:0f128d74a6ab2501a8ff43dacbb321a2b895d28560a5338b0a9f2c5ca7fcc8b3
    depends_on:
      - db
      - gotenberg
    environment:
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=alexandria
      - DATABASE_USER=alexandria
      - DATABASE_PASSWORD=alexandria
      - ALLOWED_HOSTS=dms
      - OIDC_BEARER_TOKEN_REVALIDATION_TIME=300
      - SECRET_KEY=aaa
      - DOCXTEMPLATE_JINJA_EXTENSIONS=

  gotenberg:
    image: gotenberg/gotenberg:8.37.0-libreoffice@sha256:c85f019d6ae4927714507254331cc0ed72da7b619ee798e3a45de01f54372c12
    environment:
      - CHROMIUM_DISABLE_ROUTES=true
      - PDFENGINES_DISABLE_ROUTES=true
      - WEBHOOK_DISABLE=true

  garage:
    image: dxflrs/garage:v2.4.1@sha256:9c96caa2612d3411acc5b0e6701fb238dbfba33e533a6d7d3d811a4b12d0d020
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data
    ports:
      - "3900:3900"
    environment:
      - GARAGE_DEFAULT_ACCESS_KEY=very
      - GARAGE_DEFAULT_SECRET_KEY=verysecretsecret
      - GARAGE_DEFAULT_BUCKET=alexandria-media
    command: /garage server --single-node --default-bucket

  tika:
    image: apache/tika:4.1.0-1-full@sha256:ab9cc988828c594d32d6409e1850d1c8d83152ea793ef5fe0e7862ac0f9e5891
    ports:
      - "9998:9998"

  clamav:
    image: clamav/clamav:1.5.4@sha256:ebec5bc138401b36ae987caa1a3fa3c3b2a21ed3d51f0bfa5852825e663e67b0
    ports:
      - "3310:3310"
    volumes:
      - clamav_data:/var/lib/clamav

  redis:
    image: redis:8.10.1@sha256:8a1efc5f479551822b47424ccae982026b633f28818eab0387348120a61e10e2
    volumes:
      - redis_data:/redis/data

  celery:
    <<: *alexandria-common
    image: ghcr.io/projectcaluma/alexandria-celery:dev
    volumes:
      - ./celery/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh

volumes:
  dbdata18:
  clamav_data:
  redis_data:
  garage_meta:
  garage_data:
