services:
  db:
    environment:
      - POSTGRES_PASSWORD=alexandria
    ports:
      - "5432:5432"

  media-files:
    image: alpine
    restart: "no"
    volumes:
       - uploads:/media/uploads
    entrypoint: |
      /bin/sh -c "chown -R ${UID}:${UID} /media"

  alexandria:
    build:
      context: .
      target: dev
    user: "${UID:?Set UID env variable to your user id}"
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
      - uploads:/media/uploads
    depends_on:
     - media-files
    environment:
      - ENV=dev
      - DEBUG=true
      - ALEXANDRIA_DEV_AUTH_BACKEND=true
      - ALEXANDRIA_ALLOW_ANONYMOUS_WRITE=true

  minio:
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123

  mc:
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123

  clamav:
    environment:
      - CONCURRENT_DATABASE_RELOAD=false
      - ENABLE_DEFINITIONS_UPDATE=false

volumes:
  uploads:
