---
x-alexandria-common: &alexandria-common
  image: ghcr.io/projectcaluma/alexandria:dev
  depends_on:
    - db
    - minio
    - tika
    - clamav
    - dms
  environment:
    - DATABASE_HOST=db
    - DATABASE_PORT=5432
    - TIKA_CLIENT_ONLY=true
    - TIKA_SERVER_ENDPOINT=http://tika:9998
    - ALEXANDRIA_CLAMD_TCP_ADDR=clamav

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=alexandria
      # following option is a must to configure on production system:
      # https://hub.docker.com/_/postgres
      # - POSTGRES_PASSWORD=
    volumes:
      - dbdata:/var/lib/postgresql/data

  alexandria:
    <<: *alexandria-common
    ports:
      - "8000:8000"

  dms:
    image: ghcr.io/adfinis/document-merge-service:6.4.4
    depends_on:
      - db
    environment:
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=alexandria
      - DATABASE_USER=alexandria
      - DATABASE_PASSWORD=alexandria
      - ALLOWED_HOSTS=dms
      - OIDC_BEARER_TOKEN_REVALIDATION_TIME=300
      - SECRET_KEY=aaa
      - DOCXTEMPLATE_JINJA_EXTENSIONS=

  minio:
    image: minio/minio:RELEASE.2023-11-06T22-26-08Z
    volumes:
      - minio_data:/data
    ports:
      - "443:443"
      - "9000:9000"
      - "9090:9090"
    environment:
      - MINIO_ROOT_USER=very
      - MINIO_ROOT_PASSWORD=secret
    command: server data --console-address ":9090"

  mc:
    image: minio/mc:RELEASE.2023-11-06T04-19-23Z
    restart: no
    environment:
      - MINIO_ROOT_USER=very
      - MINIO_ROOT_PASSWORD=secret
    # You might need to override the entrypoint in docker-compose.override.yml to reflect your setup
    entrypoint: >
      /bin/sh -c " mc config host add dc-minio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} --api S3v4; mc mb dc-minio/alexandria-media;"
    depends_on:
      - minio

  tika:
    image: apache/tika:2.9.2.0-full
    ports:
      - "9998:9998"

  clamav:
    image: tiredofit/clamav:2.6.17
    ports:
      - "3310:3310"

  redis:
    image: redis:7.4
    volumes:
      - redis_data:/redis/data

  celery:
    <<: *alexandria-common
    volumes:
      - ./celery/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh

volumes:
  dbdata:
  redis_data:
  minio_data:
    driver: local
