# Generated by Django 2.2.28 on 2022-07-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alexandria_core", "0002_tags_monolingual"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("undefined", "undefined"),
                    ("completed", "completed"),
                    ("error", "error"),
                ],
                default="undefined",
                max_length=32,
            ),
        ),
    ]
