# Generated by Django 2.2.28 on 2022-07-15 15:20

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alexandria_core", "0003_file_upload_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagSynonymGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_by_user",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="created by user",
                    ),
                ),
                (
                    "created_by_group",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="created by group",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "modified_by_user",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="created by user",
                    ),
                ),
                (
                    "modified_by_group",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="created by group",
                    ),
                ),
                (
                    "meta",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict, verbose_name="meta"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name="tag",
            name="tag_synonym_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tags",
                to="alexandria_core.TagSynonymGroup",
            ),
        ),
    ]
