# Generated by Django 3.2.18 on 2023-04-21 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alexandria_core", "0004_tag_synonym_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="type",
            new_name="variant",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="meta",
            new_name="metainfo",
        ),
        migrations.RenameField(
            model_name="document",
            old_name="meta",
            new_name="metainfo",
        ),
        migrations.RenameField(
            model_name="file",
            old_name="meta",
            new_name="metainfo",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="meta",
            new_name="metainfo",
        ),
        migrations.RenameField(
            model_name="tagsynonymgroup",
            old_name="meta",
            new_name="metainfo",
        ),
    ]
