# Generated by Django 3.2.18 on 2023-05-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alexandria_core", "0005_rename_type_and_meta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="metainfo",
            field=models.JSONField(default=dict, verbose_name="metainfo"),
        ),
        migrations.AlterField(
            model_name="document",
            name="metainfo",
            field=models.JSONField(default=dict, verbose_name="metainfo"),
        ),
        migrations.AlterField(
            model_name="file",
            name="metainfo",
            field=models.JSONField(default=dict, verbose_name="metainfo"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="metainfo",
            field=models.JSONField(default=dict, verbose_name="metainfo"),
        ),
        migrations.AlterField(
            model_name="tagsynonymgroup",
            name="metainfo",
            field=models.JSONField(default=dict, verbose_name="metainfo"),
        ),
    ]
