# Generated by Django 3.2.18 on 2023-05-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("alexandria_core", "0006_auto_20230504_1142"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
