# Generated by Django 3.2.22 on 2023-10-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alexandria_core", "0007_category_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
