# Generated by Django 3.2.22 on 2023-11-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alexandria_core", "0008_document_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="checksum",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="checksum"
            ),
        ),
    ]
