# Generated by Django 3.2.20 on 2023-11-10 09:54

import localized_fields.fields.text_field
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alexandria_core", "0009_file_checksum"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mark",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_by_user",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="created by user",
                    ),
                ),
                (
                    "created_by_group",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="created by group",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "modified_by_user",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="created by user",
                    ),
                ),
                (
                    "modified_by_group",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="created by group",
                    ),
                ),
                ("metainfo", models.JSONField(default=dict, verbose_name="metainfo")),
                (
                    "slug",
                    models.SlugField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "name",
                    localized_fields.fields.text_field.LocalizedTextField(
                        max_length=100, required=["en"], verbose_name="Mark name"
                    ),
                ),
                (
                    "description",
                    localized_fields.fields.text_field.LocalizedTextField(
                        blank=True,
                        null=True,
                        required=[],
                        verbose_name="Mark description",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name="document",
            name="marks",
            field=models.ManyToManyField(
                blank=True, related_name="documents", to="alexandria_core.Mark"
            ),
        ),
    ]
