# Generated by Django 3.2.23 on 2024-02-07 13:07

from django.db import migrations, models

import alexandria.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("alexandria_core", "0013_file_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="mime_type",
            field=models.CharField(default="application/octet-stream", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="file",
            name="size",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.UUIDField(
                default=alexandria.core.models.make_uuid,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
