# Generated by Django 3.2.25 on 2024-03-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alexandria_core", "0014_file_mime_type_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="modified_by_group",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="modified by group"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="modified_by_user",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="modified by user"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="modified_by_group",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="modified by group"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="modified_by_user",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="modified by user"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="modified_by_group",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="modified by group"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="modified_by_user",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="modified by user"
            ),
        ),
        migrations.AlterField(
            model_name="mark",
            name="modified_by_group",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="modified by group"
            ),
        ),
        migrations.AlterField(
            model_name="mark",
            name="modified_by_user",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="modified by user"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="modified_by_group",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="modified by group"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="modified_by_user",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="modified by user"
            ),
        ),
        migrations.AlterField(
            model_name="tagsynonymgroup",
            name="modified_by_group",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="modified by group"
            ),
        ),
        migrations.AlterField(
            model_name="tagsynonymgroup",
            name="modified_by_user",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="modified by user"
            ),
        ),
    ]
