# Generated by Django 3.2.25 on 2024-03-19 13:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alexandria_core", "0015_fix_modified_by_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="allowed_mime_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                null=True,
                size=None,
                verbose_name="allowed mime types",
            ),
        ),
    ]
