# Generated by Django 3.2.25 on 2024-05-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alexandria_core", "0016_category_allowed_mime_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="sort",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
