# Generated by Django 3.2.25 on 2024-05-03 08:21

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alexandria_core", "0016_category_allowed_mime_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="content_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name="file",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["content_vector"], name="alexandria__content_5ff46e_gin"
            ),
        ),
    ]
