# Generated by Django 4.2.15 on 2024-08-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alexandria_core", "0017_file_vector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="document description"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(
                blank=True, null=True, verbose_name="document title"
            ),
        ),
    ]
