# Generated by Django 4.2.16 on 2024-10-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alexandria_core", "0018_alter_document_description_alter_document_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="content_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
