# Generated by Django 4.2.19 on 2025-02-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alexandria_core", "0019_file_content_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("sort",)},
        ),
        migrations.AddField(
            model_name="category",
            name="sort",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
