# Generated by Django 4.2.19 on 2025-02-27 13:23

import localized_fields.fields.char_field
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alexandria_core", "0021_field_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mark",
            name="name",
            field=localized_fields.fields.char_field.LocalizedCharField(
                required=[], verbose_name="Name"
            ),
        ),
    ]
