# Generated by Django 5.2.16 on 2026-08-14 12:49

from django.db import migrations, models


def forward(apps, schema_editor):
    Category = apps.get_model("alexandria_core", "Category")

    for category in Category.objects.all():
        category._allowed_mime_types = {
            mime_type: None for mime_type in category.allowed_mime_types or []
        }
        category.save()


def reverse(apps, schema_editor):
    Category = apps.get_model("alexandria_core", "Category")

    for category in Category.objects.all():
        category.allowed_mime_types = list(category._allowed_mime_types.keys())
        category.save()


class Migration(migrations.Migration):
    dependencies = [
        ("alexandria_core", "0022_alter_mark_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="_allowed_mime_types",
            field=models.JSONField(default=dict, verbose_name="Allowed mime types"),
        ),
        migrations.RunPython(forward, reverse),
        migrations.RemoveField(model_name="category", name="allowed_mime_types"),
        migrations.RenameField(
            model_name="category",
            old_name="_allowed_mime_types",
            new_name="allowed_mime_types",
        ),
    ]
