apiVersion: v2
name: alexandria
description: Deploy the Alexandria DMS to Kubernetes
type: application
# managed by CD
version: 0.0.0
appVersion: dev
home: https://caluma.io/
icon: https://avatars0.githubusercontent.com/u/42172011?s=200&v=4
sources:
  - https://github.com/projectcaluma/emeis
  - https://github.com/projectcaluma/charts
maintainers:
  - name: projectcaluma
    email: contact@caluma.io
dependencies:
  - name: postgresql
    version: ~14.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: minio
    version: ~5.0.15
    repository: https://charts.min.io
    condition: minio.enabled
