name: PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install poetry
        run: pipx install poetry

      - name: Setup python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install apt dependencies
        uses: awalsh128/cache-apt-pkgs-action@2c09a5e66da6c8016428a2172bd76e5e4f14bb17 # v1.5.3
        with:
          packages: |
            ffmpeg
            ghostscript
            imagemagick
            inkscape
            libfile-mimeinfo-perl
            libimage-exiftool-perl
            libjpeg-dev
            libmagic1
            libreoffice
            libsecret-1-0
            poppler-utils
            webp
            zlib1g-dev
          version: 1.0

      - name: Install dependencies
        run: |
          python -m pip install -U twine
          poetry install

      - name: Build package
        run: poetry build

      - name: Upload to PyPI
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          TWINE_NON_INTERACTIVE: true
